# Numpy exercises


#### 1. Import the numpy package under the name `np` (★☆☆) `hint: import … as`

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆) `hint: vector is a single raw array`

In [23]:
n= np.zeros(10)
n

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. How to find the memory size of any array, creat a random 5x6 array and check the sizs (★☆☆)

In [75]:
x = np.random.randint(30,size=( 5, 6))
x.size

30

#### 4. How to get the documentation of the numpy add function from the command line? (★☆☆) `hint: use info or ?`

In [21]:
? np.add(x,x2)

In [19]:
x2 = np.random.randint(30,size=( 5, 6))

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆) `hint: array[x]`

In [24]:
n= np.zeros(10)
n[4]=1
n

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector (single raw array) with values ranging from 10 to 49 (★☆☆) `hint: arange`

In [53]:
m= np.arange(10,50)
m

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Show how you can Reverse a vector (first element becomes last) (★☆☆)`hint: use index of -1`

In [54]:
last=m[-1]
m[-1] =m[0]
m[0]= last
m

array([49, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) `hint: use range and reshape!`

In [56]:
matr=np.arange(0,9)
matr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆) `hint: use the np.nonzero`

In [57]:
L1=[1,2,0,0,4,0]
np.nonzero(L1)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) `hint: use index and use np.eye`
the following is an example of 5x4 identity matrix


```
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

```



In [60]:
i=np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) `hint: np.random.random`

In [64]:
j = np.random.random((3,3,3))
j

array([[[0.59937194, 0.95590212, 0.91970241],
        [0.4168151 , 0.17679563, 0.96902764],
        [0.46581413, 0.15652941, 0.58252795]],

       [[0.7596878 , 0.34860441, 0.49431857],
        [0.4859311 , 0.83495351, 0.56662962],
        [0.35281545, 0.78089314, 0.1821257 ]],

       [[0.72887027, 0.10570333, 0.97206809],
        [0.23300429, 0.27617466, 0.36100016],
        [0.30597059, 0.04046316, 0.54980908]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) `hint: min, max`

In [72]:
z = np.random.random((10,10))
minimum=np.min(z)

minimum


0.014666520765177604

In [73]:
maximum= np.max(z)
maximum

0.997223578369916

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) `hint: mean`

In [79]:
ran = np.random.randint(30)
mean=np.mean(ran)
mean

12.0

#### 15. Create a 2d array as following, with 1 on the border and 0 inside.. see generated array (★☆☆)



```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```



In [81]:
# Your code
one=np.ones((6,10))
one[1:-1,1:-1]=0
one

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★★☆) `hint: see generated array np.pad   `

In [85]:
zero=np.ones((5,5))
zero= np.pad(zero,pad_width=1,mode='constant',constant_values=0)
zero

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [86]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

 ####18  What is the result of the following expression? (★☆☆) `hint: indexing the nan using np.nan`



```
Z = np.ones((5,5))
Z[0,1]=np.nan
Z
```



In [87]:
Z = np.ones((5,5))
Z[0,1]=np.nan
Z

array([[ 1., nan,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

#### 18. Now, use this expression to find the index of your nan


```
np.argwhere(x!=x)    Hint: x is your array
```





20. Generate the following array 


```
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])
```



In [112]:
arr=([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

arr2=np.array(arr)
np.argwhere(arr2!=arr2)


array([], shape=(0, 2), dtype=int64)

In [ ]:
np.argwhere(array!=array)

#### 19. Extract the following values `array([ 1,  6, 11, 16])`. ` Hint: use np.diagonal()`

In [108]:
s1=[1,6,11,16]
s2=np.array(s1)
np.diagonal()

AttributeError: ignored

array([[ 1., nan,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

#### 20. Try to use `np.diag` to Create a 5x5 matrix with diagonal values 11,11,11,11 (★★☆) Hint: use np.diag with k=0 and [11,11,11,11]. -- diag([11,11,11,11],k=-0)

In [115]:
d=np.diag([11,11,11,11,11],k=0)
d

array([[11,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0],
       [ 0,  0, 11,  0,  0],
       [ 0,  0,  0, 11,  0],
       [ 0,  0,  0,  0, 11]])

#### 21.  Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) `Hint: use k=-1 when calling np.diag`

In [116]:
e=np.diag([1,2,3,4],k=-1)
e

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

####22. Create a 8x8 matrix and fill it with a given pattern (★☆☆) Hint: use np.zeros and do the replace 



```
[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]
```



In [121]:
f=np.zeros((8,8))
f.astype(str)


array([['0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
       ['0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
       ['0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
       ['0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
       ['0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
       ['0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
       ['0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
       ['0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0']],
      dtype='<U32')

In [124]:
f[1::2,::2] = 'O'
f[0::2,::2] =''
f[2::2,::2] ='M'

ValueError: ignored

#### 23. Use the `np.tile` to generate the same pattern 

```
[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]
```



[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]


#### 24. Generate then Normalize a 5x5 random matrix (★☆☆)  `hint: Normalization_array = (x_arr -mean_value(x))/std_value(x)`

In [126]:
nor = np.random.random((5,5))
mean_value = np.mean(nor)
std_value = np.std(nor)
Normalization_array =(nor  - mean_value(x))/std_value(x)


NameError: ignored

#### 25. generate any 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

where 

```
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
```
will return

```
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
```




In [ ]:
p = np.arange(11)
for 
# Your code here!. 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 26. Consider an integer vector Z, comment any iligal expressions (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 27. Generate two randon 1D array, How to find common values between two arrays? (★☆☆) `Hint: use intersect1d(Arr1,Arr2)`

#### 28. How to ignore all numpy warnings (not recommended)? (★☆☆)

####29. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```